### PR TITLE
Block UI on click

### PR DESCRIPTION
**Pull request by huyndo**
Adds a loading model to block UI when waiting for commands to finish. Similar to this [PR](https://github.com/onflow/wallet-extension-example/commit/4f328d5bcb936944fb90a1ff3a2a75388241eaa2) in extension-example.

### CODE REVIEW

**Review by gregsantos — APPROVED** [review]
looks good. need to fix confilcts and i'll merge

**Comment by huyndo** [comment]
@gregsantos You mind checking what's wrong in Vercel bc I don't have an account there apparently

**Review by gregsantos — CHANGES_REQUESTED** [review]
Should we add loading handler for discovery api options?

**Comment by huyndo** [comment]
> Should we add loading handler for discovery api options?

Added sir

**Review by gregsantos — APPROVED** [review]

**Pull request merged**
